version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:3000" # Assuming your frontend runs on port 3000 inside the container
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:3000" # Assuming your backend runs on port 3000 inside the container
